# 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np

null_vector = np.zeros(10)

null_vector[4] = 1

null_vector


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 2.create a vector with values ranging from 10 to 49.

In [2]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 3.Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
import numpy as np
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 4.Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
non_zero_indices

(array([0, 1, 4], dtype=int64),)

# 5.Create a 10x10 array with random values and find the minimum and maximum values.

In [13]:
import numpy as np

random_array = np.random.randint(0,100,(10, 10))


min_value = random_array.min()
max_value = random_array.max()
print(random_array)
print(min_value)
print(max_value)

[[40  2 81 25 58 25 11 99 38 10]
 [13 62 97  1 10 43 18 66 46 23]
 [16 65 27 14 73 21 99 14 79 51]
 [ 8 65 23 93  8  7 43 68 17 26]
 [92 22 64 30 68 82 30 83 67 85]
 [ 2 16 80 69 42 22 48 49 65 95]
 [99 73 49 16 61 98  8 33  6 66]
 [23 61 47 83 34 17 42 83 43 32]
 [ 0 64  5 44 59 98 43 63 42  0]
 [27 98 39 43 64 99 62 14 11 53]]
0
99


# 6. Create a random vector of size 30 and find the mean value.


In [16]:
import numpy as np

random_vector = np.random.randint(2,30,90)

mean_value = random_vector.mean()
mean_value 

16.08888888888889